# Generated by Django 3.2.5 on 2021-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(upload_to='cms/static/images/projects', verbose_name='Фото'),
        ),
    ]
