# Generated by Django 3.2.5 on 2021-07-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210730_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проекты', 'verbose_name_plural': 'Проект'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Команда'},
        ),
    ]
