# Generated by Django 3.2.5 on 2021-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_projects_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/badges')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='location',
            field=models.CharField(default='Локация', max_length=300),
        ),
        migrations.AlterField(
            model_name='projects',
            name='photo',
            field=models.ImageField(upload_to='media/projects-photo/', verbose_name='Фот'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='Название', max_length=300),
        ),
    ]
