# Generated by Django 3.2.5 on 2021-07-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210731_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBadges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/contact-badges')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Значок контактов',
                'verbose_name_plural': 'Значки контактов',
            },
        ),
        migrations.AlterModelOptions(
            name='badges',
            options={'verbose_name': 'Значок с главной', 'verbose_name_plural': 'Значки с главной'},
        ),
        migrations.AlterField(
            model_name='badges',
            name='photo',
            field=models.ImageField(upload_to='media/index-badges/'),
        ),
    ]
