# Generated by Django 3.2.5 on 2021-07-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210731_1307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Badges',
            new_name='IndexBadges',
        ),
    ]
