# Generated by Django 3.2.5 on 2021-08-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_rename_badges_indexbadges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
